name: '持续集成'

on:
  # 注释掉自动触发条件
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master
  
  # 改为只有手动触发
  workflow_dispatch:
    inputs:
      reason:
        description: '运行原因'
        required: false
        default: '手动触发构建'

jobs:
  test-build:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            libgtk-3-0 \
            libnss3 \
            libxss1 \
            libasound2 \
            libx11-xcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxi6 \
            libxtst6 \
            libxrandr2 \
            libgbm1 \
            libegl1 \
            libgl1-mesa-glx \
            libdrm2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          cache: true

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Cache AppImage tools
        if: matrix.platform == 'ubuntu-22.04'
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/tauri-action
            ~/.cache/appimage-builder
          key: ${{ runner.os }}-appimage-tools-${{ hashFiles('src-tauri/tauri.conf.json') }}
          restore-keys: |
            ${{ runner.os }}-appimage-tools-

      - name: Install frontend dependencies
        run: bun install

      - name: Build the app (debug mode)
        run: bun run tauri build --debug