name: 'Release'

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            libgtk-3-0 \
            libnss3 \
            libxss1 \
            libasound2 \
            libx11-xcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxi6 \
            libxtst6 \
            libxrandr2 \
            libgbm1 \
            libegl1 \
            libgl1-mesa-glx \
            libdrm2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          cache: true

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Cache AppImage tools
        if: matrix.platform == 'ubuntu-22.04'
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/tauri-action
            ~/.cache/appimage-builder
          key: ${{ runner.os }}-appimage-tools-${{ hashFiles('src-tauri/tauri.conf.json') }}
          restore-keys: |
            ${{ runner.os }}-appimage-tools-

      - name: Install frontend dependencies
        run: bun install

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Stock App ${{ github.ref_name }}'
          releaseBody: '请查看资源以下载并安装此版本。'
          releaseDraft: false
          prerelease: false